{"name": "Fail to loging into the system with unknown user credentials", "status": "passed", "description": "Trying to Login with unknown user credentials", "steps": [{"name": "Login with Username: 'JohnDoe11' and Password: 'Pass1234!'", "status": "passed", "parameters": [{"name": "username", "value": "'JohnDoe11'"}, {"name": "password", "value": "'Pass1234!'"}], "start": 1736955348559, "stop": 1736955349481}, {"name": "Get error message", "status": "passed", "start": 1736955349481, "stop": 1736955349629}], "attachments": [{"name": "log", "source": "d8e8680f-20a6-4a90-8177-c90747da8696-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "c1b99ead-a256-43c0-9ce0-8c3faba71fe3-attachment.txt", "type": "text/plain"}], "start": 1736955348549, "stop": 1736955349629, "uuid": "64995cc8-e0f7-4e09-8dd6-b106dacbc03e", "historyId": "833f0a6b9a8d9f5c50bf6905da0bfbb6", "testCaseId": "833f0a6b9a8d9f5c50bf6905da0bfbb6", "fullName": "test_login_page.TestLoginPage#test_locked_user_login", "labels": [{"name": "epic", "value": "Security"}, {"name": "feature", "value": "Login"}, {"name": "story", "value": "Login using unknown user credentials"}, {"name": "severity", "value": "blocker"}, {"name": "suite", "value": "test_login_page"}, {"name": "subSuite", "value": "TestLoginPage"}, {"name": "host", "value": "DESKTOP-52FQS7R"}, {"name": "thread", "value": "45372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_page"}]}